version: '3.9'
services:
    server:
        build:
            context: .
            dockerfile: docker/alpine-unit/Dockerfile
            args:
              - GIT_EMAIL=${GIT_EMAIL}
              - GIT_NAME=${GIT_NAME}
              - PHPVERSION=${PHPVERSION}
        container_name: ${COMPOSE_PROJECT_NAME}-server
        ports:
            - "80:80"
            - "9003:9003"
        volumes:
            - .:/www:rw

    postgres:
        build:
            context: ./docker/postgres
        container_name: ${COMPOSE_PROJECT_NAME}-postgres
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data:rw
        user: "${UID}:${GID}"
